Ctctraders 2134 Validate that a user can make an unloading remarks
hmrc/declare-transit-movement-unloading-frontend pull request #156
Opened 2021-04-22 14:57 UTC by sawan07

2021-04-23 13:30 UTC, amaalali requested changes

2021-04-23 13:30 UTC, amaalali commented on app/controllers/actions/CheckArrivalStatus.scala
> +    extends ActionRefiner[IdentifierRequest, AuthorisedRequest] {
Because IdentifierRequest and AuthorisedRequest are the same there is no need for AuthorisedRequest as a new class. This means we can simplify this to an ActionFilter

2021-04-23 14:43 UTC, sawan07 commented on app/controllers/actions/CheckArrivalStatus.scala
> +    extends ActionRefiner[IdentifierRequest, AuthorisedRequest] {
done!

2021-04-26 09:11 UTC, amaalali approved these changes

2021-04-26 09:14 UTC, merged